#!/usr/bin/env bash
# script to configure broken container to work with nginx at port 8080
# restart nginx as nginx user
wget -O do_fix https://https://raw.github.com/Johntista85/alx-system_engineering-devops/master/0x12-web_stack_debugging_2/1-run_nginx_as_nginx
chmod u+x do_fix
./do_fix
