#!/usr/bin/env bash

# display contents of the current directory in a list format
# excluding hidden files and showing only the part of the name after the first dash

ls | grep -v '^\.' | sed 's/^[^-]*-//'
